version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - ./assets/video:/app/assets/video
    command: bundle exec jekyll serve --host=0.0.0.0 --watch