version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    ports:
      - "14000:4000"
    volumes:
      - .:/srv/jekyll
      - gem_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=production
    command: >
      sh -c "
        gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/ &&
        bundle config mirror.https://rubygems.org https://gems.ruby-china.com &&
        bundle config retry 5 &&
        bundle config timeout 600 &&
        bundle check || bundle install &&
        jekyll build --incremental &&
        jekyll serve --host 0.0.0.0 --skip-initial-build --no-watch
      "

volumes:
  gem_cache:
